---
- include_tasks: is_systemd.yml

# Variable configuration.
- include_tasks: variables.yml

- name: Add the ansible group
  group:
    name: "{{ new_ansible_group }}"
    state: present

- name: Add the ansible user
  user:
    name: "{{ new_ansible_user }}"
    password_lock: true
    shell: /bin/bash
    append: true
    state: present

- name: Add the docker API
  pip:
    name: "docker"

- name: Ensure system script path exists
  file:
    path: "/home/{{ new_ansible_user }}/system"
    owner: "{{ new_ansible_user }}"
    group: "{{ new_ansible_group }}"
    state: directory
    mode: 0700
    recurse: true

- name: Ensure ansible packages are installed.
  apt:
    name: "{{ ansible_packages }}"
    state: present

- name: Install collections from Ansible Galaxy
  command: "ansible-galaxy collection install {{ item }}"
  loop: "{{ ansible_galaxy_collections }}"

