---
# Variable configuration.
- name: Check os and version
  debug:
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}"

- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution != 'Fedora'

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Fedora'

- name: Define ansible_packages.
  set_fact:
    ansible_packages: "{{ __ansible_packages | list }}"
  when: ansible_packages is not defined

- name: Define ansible_version.
  set_fact:
    ansible_version: "{{ __ansible_version }}"
  when: ansible_version is not defined

- name: Define ansible_bin_path.
  set_fact:
    ansible_bin_path: "{{ __ansible_bin_path }}"
  when: ansible_bin_path is not defined

- name: Define ansible_config_path.
  set_fact:
    ansible_config_path: "{{ __ansible_config_path }}"
  when: ansible_config_path is not defined
